INDIGO_WELCOME_MESSAGE: ""
INDIGO_PRIMARY_COLOR: "#3b85ff" # cool blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: ""
    url: ""
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "Â© 2020 Digital Generation, by Raisense. All rights reserved"
      url: "/"
